In [10]:
import os
import pandas as pd

df = pd.read_csv("C:\\Users\\ABHIJEET\\OneDrive\\Fore\\Trimester 1\\Python\\Sample - Superstore.csv", encoding='ISO-8859-1')
df.shape

(9994, 21)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [16]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [18]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [20]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [60]:
sample_df = df.sample(n = 2000,replace = False, random_state=55002)
sample_df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1091,1092,CA-2015-143490,12/6/2015,12/13/2015,Standard Class,NP-18325,Naresj Patel,Consumer,United States,San Diego,...,92105,West,OFF-AR-10002952,Office Supplies,Art,Stanley Contemporary Battery Pencil Sharpeners,120.150,9,0.0,33.6420
4721,4722,CA-2014-106229,6/7/2014,6/11/2014,Second Class,NR-18550,Nick Radford,Consumer,United States,Aurora,...,60505,Central,FUR-TA-10002041,Furniture,Tables,"Bevis Round Conference Table Top, X-Base",268.935,3,0.5,-209.7693
4668,4669,US-2017-133200,5/6/2017,5/11/2017,Standard Class,DB-13555,Dorothy Badders,Corporate,United States,Fort Worth,...,76106,Central,OFF-BI-10002827,Office Supplies,Binders,Avery Durable Poly Binders,11.060,10,0.8,-18.8020
2018,2019,CA-2015-113110,3/19/2015,3/23/2015,Standard Class,BK-11260,Berenike Kampe,Consumer,United States,San Bernardino,...,92404,West,OFF-SU-10001165,Office Supplies,Supplies,Acme Elite Stainless Steel Scissors,33.360,4,0.0,8.6736
3294,3295,CA-2014-138023,8/15/2014,8/18/2014,First Class,KH-16510,Keith Herrera,Consumer,United States,Dallas,...,75081,Central,OFF-BI-10003638,Office Supplies,Binders,GBC Durable Plastic Covers,30.960,8,0.8,-52.6320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4699,4700,CA-2017-140298,5/11/2017,5/17/2017,Standard Class,JK-16120,Julie Kriz,Home Office,United States,Austin,...,78745,Central,OFF-AR-10003481,Office Supplies,Art,Newell 348,5.248,2,0.2,0.5904
7895,7896,CA-2017-124744,6/21/2017,6/25/2017,Standard Class,EH-14125,Eugene Hildebrand,Home Office,United States,Wheeling,...,26003,East,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,6.240,2,0.0,3.0576
1673,1674,CA-2015-150560,12/11/2015,12/12/2015,First Class,SW-20455,Shaun Weien,Consumer,United States,Suffolk,...,23434,South,OFF-LA-10003930,Office Supplies,Labels,"Dot Matrix Printer Tape Reel Labels, White, 50...",196.620,2,0.0,96.3438
4558,4559,CA-2014-127383,12/31/2014,1/5/2015,Standard Class,CM-11815,Candace McMahon,Corporate,United States,El Paso,...,79907,Central,OFF-EN-10004773,Office Supplies,Envelopes,Staple envelope,49.568,2,0.2,17.9684
2594,2595,CA-2017-149048,5/13/2017,5/17/2017,Standard Class,BM-11650,Brian Moss,Corporate,United States,Columbus,...,47201,Central,OFF-EN-10003296,Office Supplies,Envelopes,Tyvek Side-Opening Peel & Seel Expanding Envel...,180.960,2,0.0,81.4320

In [50]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 1091 to 2594
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2000 non-null   int64
 1   Order ID       2000 non-null   object
 2   Order Date     2000 non-null   object
 3   Ship Date      2000 non-null   object
 4   Ship Mode      2000 non-null   object
 5   Customer ID    2000 non-null   object
 6   Customer Name  2000 non-null   object
 7   Segment        2000 non-null   object
 8   Country        2000 non-null   object
 9   City           2000 non-null   object
 10  State          2000 non-null   object
 11  Postal Code    2000 non-null   int64
 12  Region         2000 non-null   object
 13  Product ID     2000 non-null   object
 14  Category       2000 non-null   object
 15  Sub-Category   2000 non-null   object
 16  Product Name   2000 non-null   object
 17  Sales          2000 non-null   float64
 18  Quantity       2000 non-null   int64
 19  Discount       2000 non-null   float64
 20  Profit         2000 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 343.8+ KB

In [52]:
sample_df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,4988.823500,54849.206000,220.940689,3.786000,0.157210,28.159083
std,2861.948472,31985.234673,520.186436,2.229953,0.207789,193.537414
min,1.000000,1453.000000,0.444000,1.000000,0.000000,-3399.980000
25%,2565.750000,23602.000000,17.940000,2.000000,0.000000,1.877000
50%,4909.000000,55078.500000,54.256000,3.000000,0.200000,9.154950
75%,7492.000000,90004.000000,209.970000,5.000000,0.200000,31.018400
max,9994.000000,99301.000000,9449.950000,14.000000,0.800000,4630.475500

In [74]:
sample_df.head()

      Row ID        Order ID Order Date   Ship Date       Ship Mode Customer ID    Customer Name    Segment        Country            City  ... Postal Code   Region       Product ID         Category Sub-Category                                    Product Name    Sales  Quantity  Discount    Profit
1091    1092  CA-2015-143490  12/6/2015  12/13/2015  Standard Class    NP-18325     Naresj Patel   Consumer  United States       San Diego  ...       92105     West  OFF-AR-10002952  Office Supplies          Art  Stanley Contemporary Battery Pencil Sharpeners  120.150         9       0.0   33.6420
4721    4722  CA-2014-106229   6/7/2014   6/11/2014    Second Class    NR-18550     Nick Radford   Consumer  United States          Aurora  ...       60505  Central  FUR-TA-10002041        Furniture       Tables        Bevis Round Conference Table Top, X-Base  268.935         3       0.5 -209.7693
4668    4669  US-2017-133200   5/6/2017   5/11/2017  Standard Class    DB-13555  Dorothy Badders  Corporate  United States      Fort Worth  ...       76106  Central  OFF-BI-10002827  Office Supplies      Binders                      Avery Durable Poly Binders   11.060        10       0.8  -18.8020
2018    2019  CA-2015-113110  3/19/2015   3/23/2015  Standard Class    BK-11260   Berenike Kampe   Consumer  United States  San Bernardino  ...       92404     West  OFF-SU-10001165  Office Supplies     Supplies             Acme Elite Stainless Steel Scissors   33.360         4       0.0    8.6736
3294    3295  CA-2014-138023  8/15/2014   8/18/2014     First Class    KH-16510    Keith Herrera   Consumer  United States          Dallas  ...       75081  Central  OFF-BI-10003638  Office Supplies      Binders                      GBC Durable Plastic Covers   30.960         8       0.8  -52.6320

[5 rows x 21 columns]

In [80]:
sample_df.tail(2)

      Row ID        Order ID  Order Date  Ship Date       Ship Mode Customer ID    Customer Name    Segment        Country      City  ... Postal Code   Region       Product ID         Category Sub-Category                                       Product Name    Sales  Quantity  Discount   Profit
4558    4559  CA-2014-127383  12/31/2014   1/5/2015  Standard Class    CM-11815  Candace McMahon  Corporate  United States   El Paso  ...       79907  Central  OFF-EN-10004773  Office Supplies    Envelopes                                    Staple envelope   49.568         2       0.2  17.9684
2594    2595  CA-2017-149048   5/13/2017  5/17/2017  Standard Class    BM-11650       Brian Moss  Corporate  United States  Columbus  ...       47201  Central  OFF-EN-10003296  Office Supplies    Envelopes  Tyvek Side-Opening Peel & Seel Expanding Envel...  180.960         2       0.0  81.4320

[2 rows x 21 columns]

In [ ]:
# Figure out what are non categorical varible, then find categorical, then ordinal and nominal
# Categorical varible Nominal: Order Date, Ship Date, Ship Mode, Customer Name, Segment, Postal Code, State,Country, City, Region, Product Name
# Categorical varible Ordinal: Quantity, Discount, Sales
# Non Categorical varible: 	Profit, Category, Sub-Category